select top 10 * from customer_behavior

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer_behavior
group by gender 


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) as avg_purrchase_amount from customer_behavior)


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5
item_purchased, cast(avg(review_rating) as decimal(10,2)) as avg_rating
from customer_behavior
group by item_purchased 
order by avg_rating desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) as avg_amount 
from customer_behavior
where shipping_type in('Standard', 'Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5 item_purchased,
      100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) AS discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select case 
  when previous_purchases <=2 then 'New'
  when previous_purchases >2 and previous_purchases <=10 then 'Returning' 
  else 'Loyal'
  end
  as segment_customer, 
  count(customer_id) as total_customer
from customer_behavior
group by case 
  when previous_purchases <=2 then 'New'
  when previous_purchases >2 and previous_purchases <=10 then 'Returning' 
  else 'Loyal'
  end
order by total_customer desc


--Q8. What are the top 3 most purchased products within each category?
with ranked as (
select category, item_purchased, count(*) as total_amount,
row_number() over (partition by category order by count(*) desc) as rank
from customer_behavior
group by category,item_purchased
)
select category, item_purchased, total_amount, rank
from ranked
where rank <=3
order by category,rank 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers 
from customer_behavior
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc